// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmr0XhZcUdK6dDtFiD_RlnnGOeXBQLwF0',
    appId: '1:884766744237:web:a71ffa3f8b0fda976c7024',
    messagingSenderId: '884766744237',
    projectId: 'auth-with-g10',
    authDomain: 'auth-with-g10.firebaseapp.com',
    storageBucket: 'auth-with-g10.appspot.com',
    measurementId: 'G-GW9ZMSVKS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtE4hAMBS04nLt2HXN0NCBX2cOFswpsfU',
    appId: '1:884766744237:android:ef9161525d5605136c7024',
    messagingSenderId: '884766744237',
    projectId: 'auth-with-g10',
    storageBucket: 'auth-with-g10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCPAxdg8BEhhtLM-nSLGh8c7y6vh67Rc',
    appId: '1:884766744237:ios:204b46b7493c75ba6c7024',
    messagingSenderId: '884766744237',
    projectId: 'auth-with-g10',
    storageBucket: 'auth-with-g10.appspot.com',
    iosBundleId: 'com.pdp.learnAuthWithG10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCPAxdg8BEhhtLM-nSLGh8c7y6vh67Rc',
    appId: '1:884766744237:ios:204b46b7493c75ba6c7024',
    messagingSenderId: '884766744237',
    projectId: 'auth-with-g10',
    storageBucket: 'auth-with-g10.appspot.com',
    iosBundleId: 'com.pdp.learnAuthWithG10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmr0XhZcUdK6dDtFiD_RlnnGOeXBQLwF0',
    appId: '1:884766744237:web:96ef9283632641066c7024',
    messagingSenderId: '884766744237',
    projectId: 'auth-with-g10',
    authDomain: 'auth-with-g10.firebaseapp.com',
    storageBucket: 'auth-with-g10.appspot.com',
    measurementId: 'G-03XFF08FKN',
  );
}
